# Generated by Django 2.2.20 on 2021-04-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='date',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='file_field',
            field=models.CharField(max_length=250),
        ),
    ]
